import Provider from "@/components/Provider";
import { Toaster } from "sonner";

export const metadata = {
  title: "Proyecto P1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
